template: true   # required for local templates
valuesFilePath: ./values.yml

pipelines:
  - name: pipe1
    steps:
      - name: test_step_1
        type: Bash
        configuration:
          integrations:
            - name: mySlack       # This is the name of the Slack integration you created in your test instance
        execution:
          onStart:
            - send_notification mySlack --text "starting test_step_1"         # replace 'mySlack' with the name of your Slack integration
          onExecute:
            - send_notification mySlack --text "onExecute, past test commands"  # replace 'mySlack' with the name of your Slack integration
          onSuccess:
            - send_notification mySlack      # without '--text' to send a generic notification that includes the pipeline name and step name